// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA48czqwXS1Ry7QwLLwHPAdiWHsCMmC9TY',
    appId: '1:945804263:web:8e6dab7adbc66e11fe6342',
    messagingSenderId: '945804263',
    projectId: 'advanced-homework-2',
    authDomain: 'advanced-homework-2.firebaseapp.com',
    storageBucket: 'advanced-homework-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2RbXHUZiOKBB-vWcYx0Yu3VEgF2giIHY',
    appId: '1:945804263:android:4a73b7ba4650ee3bfe6342',
    messagingSenderId: '945804263',
    projectId: 'advanced-homework-2',
    storageBucket: 'advanced-homework-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm-Wws_49YXxyaiX284nU3QZQXSEsr3hU',
    appId: '1:945804263:ios:3ed993727ed1bb61fe6342',
    messagingSenderId: '945804263',
    projectId: 'advanced-homework-2',
    storageBucket: 'advanced-homework-2.appspot.com',
    iosClientId: '945804263-c4gcbcr7qjdsrah4cejm0h4bpba7k2fr.apps.googleusercontent.com',
    iosBundleId: 'com.example.advancedHomework2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm-Wws_49YXxyaiX284nU3QZQXSEsr3hU',
    appId: '1:945804263:ios:3ed993727ed1bb61fe6342',
    messagingSenderId: '945804263',
    projectId: 'advanced-homework-2',
    storageBucket: 'advanced-homework-2.appspot.com',
    iosClientId: '945804263-c4gcbcr7qjdsrah4cejm0h4bpba7k2fr.apps.googleusercontent.com',
    iosBundleId: 'com.example.advancedHomework2',
  );
}
